#!/usr/bin/env bash
set -euo pipefail

OUTPUT="${1:-janzowm/BuildInfo.swift}"
CONFIG="${2:-Debug}"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "")"
if [[ -z "$REPO_ROOT" ]]; then
    TAG="v0.0"
    COMMITS="0"
    SHA="unknown"
    DIRTY=0
else
    cd "$REPO_ROOT"
    RAW="$(git describe --tags --long --dirty --match 'v*' 2>/dev/null || echo "")"
    if [[ -z "$RAW" ]]; then
        TAG="v0.0"
        COMMITS="0"
        SHA="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
        DIRTY=0
    else
        DIRTY=0
        if [[ "$RAW" == *-dirty ]]; then
            DIRTY=1
            RAW="${RAW%-dirty}"
        fi
        SHA="${RAW##*-g}"
        WITHOUT_SHA="${RAW%-g*}"
        COMMITS="${WITHOUT_SHA##*-}"
        TAG="${WITHOUT_SHA%-*}"
    fi
fi

VERSION="${TAG#v}"
FULL_VERSION="${VERSION}.${COMMITS}"

DISPLAY="$FULL_VERSION+$SHA"
if [[ $DIRTY -eq 1 ]]; then
    DISPLAY="${DISPLAY}-dirty"
fi
if [[ "$CONFIG" == "Debug" ]]; then
    DISPLAY="${DISPLAY} (dev)"
fi

DIRTY_BOOL=$([ $DIRTY -eq 1 ] && echo true || echo false)

NEW_CONTENT="// Generated by scripts/generate_version.sh. Do not edit.
enum BuildInfo {
    static let fullVersion = \"$FULL_VERSION\"
    static let commitSHA = \"$SHA\"
    static let isDirty = $DIRTY_BOOL
    static let configuration = \"$CONFIG\"
    static let displayString = \"$DISPLAY\"
}
"

mkdir -p "$(dirname "$OUTPUT")"
if [[ -f "$OUTPUT" ]] && [[ "$(cat "$OUTPUT")" == "$NEW_CONTENT" ]]; then
    exit 0
fi
printf '%s' "$NEW_CONTENT" > "$OUTPUT"
